# Generated by Django 5.0.2 on 2026-06-03

from django.db import migrations

def seed_remedia(apps, schema_editor):
    Project = apps.get_model('portfolio', 'Project')
    ProjectCategory = apps.get_model('portfolio', 'ProjectCategory')
    Technology = apps.get_model('portfolio', 'Technology')
    CustomUser = apps.get_model('authentication', 'CustomUser')
    
    # 1. Get or create owner
    owner = CustomUser.objects.first()
    if not owner:
        owner = CustomUser.objects.create(
            username='souleymane',
            email='soulemaneyeo99@gmail.com',
            first_name='Souleymane',
            last_name='Yeo',
            is_active=True,
            is_staff=True,
            is_superuser=True
        )
        
    # 2. Create or get category
    category_name = "IA & Environnement / IoT"
    category, _ = ProjectCategory.objects.get_or_create(
        name=category_name,
        defaults={
            "slug": "ia-environnement-iot",
            "description": "Solutions IA pour la biodiversité, la préservation des écosystèmes et le monitoring environnemental."
        }
    )
    
    # 3. Create or get technologies
    tech_data = [
        {"name": "React.js", "color": "#61dafb"},
        {"name": "FastAPI", "color": "#009688"},
        {"name": "PostgreSQL", "color": "#336791"},
        {"name": "Flutter", "color": "#02569B"},
        {"name": "Mistral", "color": "#ff5f00"},
        {"name": "LLaVA", "color": "#8b5cf6"},
        {"name": "Ollama", "color": "#000000"},
        {"name": "ESP32", "color": "#e67e22"},
        {"name": "Tailwind CSS", "color": "#06b6d4"},
        {"name": "Leaflet", "color": "#2ecc71"}
    ]
    
    techs = []
    for tech_item in tech_data:
        tech, _ = Technology.objects.get_or_create(
            name=tech_item["name"],
            defaults={"color": tech_item["color"]}
        )
        techs.append(tech)

    # 4. Create project
    detailed_desc = """REMÉDIA est une plateforme web et mobile de conservation de la biodiversité qui combine intelligence artificielle, science citoyenne, cartographie environnementale, reboisement participatif et monitoring par capteurs IoT afin de protéger, valoriser et suivre les plantes de manière durable. Le projet a été récompensé par la **3e place du Hackathon du Gnambélé Boot Camp 2025** organisé par le Programme des Nations Unies pour le Développement (PNUD Côte d'Ivoire).

    🎯 **Contexte & Hackathon** :
    Conçu lors du Gnambélé Boot Camp 2025 au Jardin Botanique de Bingerville sous la thématique *« L'intelligence artificielle au service de la biodiversité, de la lutte contre les espèces exotiques envahissantes et des services écosystémiques »*, REMÉDIA a été primé parmi plusieurs équipes.

    🚀 **Le Problème Résolu** :
    La perte de la biodiversité végétale, le déclin des savoirs traditionnels sur les plantes, l'absence de données écologiques locales fiables en temps réel et le manque d'outils accessibles pour que les citoyens participent activement à la protection de l'environnement.

    ⚙️ **Évolution & Concept** :
    D'abord simple scanner de plantes lors du hackathon, REMÉDIA a évolué pour devenir une solution complète alliant :
    - **🌿 Conservation** : Protection active des plantes.
    - **🤖 Intelligence Artificielle** : Identification automatique et diagnostic de santé.
    - **🌍 Science Citoyenne** : Collecte collaborative de signalements de plantes.
    - **🌱 Reboisement** : Mobilisation et suivi communautaire (Mission Racines).
    - **📡 Monitoring Environnemental** : Télémétrie par capteurs connectés (ESP32).

    📊 **Fonctionnalités Clés** :
    - **Scanner Intelligent** : Identification instantanée du nom scientifique et diagnostic de maladies des plantes par analyse d'image IA.
    - **Fiches Scientifiques Détaillées** : Description, composés actifs, propriétés thérapeutiques, statut de conservation UICN et géolocalisation.
    - **Assistant IA Spécialisé** : Chatbot environnemental pour assister les utilisateurs dans les pratiques de durabilité et de soin des plantes.
    - **Carte Collaborative** : Cartographie participative pour répertorier et localiser les espèces végétales sur le terrain.
    - **Mission Racines** : Gamification du reboisement où les citoyens déclarent les arbres plantés, relèvent des défis et gagnent des badges.
    - **Monitoring IoT** : Suivi en temps réel de la température, de l'humidité, de la luminosité et du pH du sol via des capteurs ESP32.

    🛠️ **Technologies Utilisées** :
    - **Frontend** : *React.js*, *Tailwind CSS* et *Leaflet* (pour les cartes collaboratives).
    - **Backend** : *FastAPI* avec *PostgreSQL* et *SQLAlchemy*.
    - **Mobile** : *Flutter* (application cross-platform).
    - **IA** : Modèles open-source (*Mistral*, *Mixtral*, *LLaVA*) orchestrés en local via *Ollama*.
    - **IoT** : Protocole *MQTT*, microcontrôleurs *ESP32* et capteurs de sol.

    👨‍💻 **Mon Rôle (Lead Technique)** :
    En tant que co-concepteur et Lead Technique, j'ai conçu l'architecture technique, développé l'interface web React, implémenté l'intégration des modèles d'IA et de chatbot, et structuré la vision de la plateforme post-hackathon."""

    project, created = Project.objects.get_or_create(
        title="REMÉDIA",
        defaults={
            "slug": "remedia",
            "description": "Intelligence Artificielle au service de la Biodiversité et de la préservation écologique.",
            "detailed_description": detailed_desc.strip(),
            "featured_image": "projects/featured/remedia_hero.png",
            "demo_url": "https://remediav2.vercel.app/",
            "source_url": "#",
            "status": "published",
            "featured": True,
            "owner": owner,
            "category": category
        }
    )
    
    if not created:
        project.owner = owner
        project.category = category
        project.save()
        
    project.technologies.set(techs)

def remove_remedia(apps, schema_editor):
    Project = apps.get_model('portfolio', 'Project')
    Project.objects.filter(slug='remedia').delete()

class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_seed_assurai'),
    ]

    operations = [
        migrations.RunPython(seed_remedia, reverse_code=remove_remedia),
    ]
