# Generated by Django 5.0.2 on 2026-06-03

from django.db import migrations

def seed_amazoon(apps, schema_editor):
    Project = apps.get_model('portfolio', 'Project')
    ProjectCategory = apps.get_model('portfolio', 'ProjectCategory')
    Technology = apps.get_model('portfolio', 'Technology')
    CustomUser = apps.get_model('authentication', 'CustomUser')

    # 1. Get or create owner
    owner = CustomUser.objects.first()
    if not owner:
        owner = CustomUser.objects.create(
            username='souleymane',
            email='soulemaneyeo99@gmail.com',
            first_name='Souleymane',
            last_name='Yeo',
            is_active=True,
            is_staff=True,
            is_superuser=True
        )

    # 2. Create or get category
    category, _ = ProjectCategory.objects.get_or_create(
        name="IA & EdTech / Voice",
        defaults={
            "slug": "ia-edtech-voice",
            "description": "Plateformes d'apprentissage vocales et intelligentes pour l'inclusion numérique."
        }
    )

    # 3. Create or get technologies
    tech_data = [
        {"name": "FastAPI",       "color": "#009688"},
        {"name": "Flutter",       "color": "#02569B"},
        {"name": "GPT-4o",        "color": "#10a37f"},
        {"name": "Whisper",       "color": "#f59e0b"},
        {"name": "ElevenLabs",    "color": "#7c3aed"},
        {"name": "FAISS",         "color": "#1d4ed8"},
        {"name": "PostgreSQL",    "color": "#336791"},
        {"name": "Docker",        "color": "#2496ed"},
        {"name": "Caddy",         "color": "#22c55e"},
    ]
    techs = []
    for t in tech_data:
        tech, _ = Technology.objects.get_or_create(
            name=t["name"], defaults={"color": t["color"]}
        )
        techs.append(tech)

    # 4. Build detailed description
    detailed_desc = """AmazoOn est une plateforme d'apprentissage numérique interactive conçue pour les femmes entrepreneures et commerçantes d'Afrique de l'Ouest, qui font face à des barrières d'accès aux technologies numériques. Le projet propose un **chatbot éducatif vocal et intelligent** capable de converser naturellement en français local avec une interface entièrement optimisée pour la voix.

    🎯 **Le Problème Résolu** :
    L'alphabétisation variable et la complexité des interfaces textuelles classiques freinent l'adoption d'outils numériques (Facebook Messenger, WhatsApp Business, Mobile Money) par de nombreuses femmes entrepreneures. AmazoOn rend la technologie accessible par la voix.

    🚀 **La Solution AmazoOn** :
    Un chatbot vocal bidirectionnel où l'utilisatrice peut poser ses questions à voix haute (ex: "Comment créer ma page Facebook ?"), uploader des documents (factures, contrats), et recevoir des conseils pédagogiques hautement personnalisés. L'IA utilise des analogies simples et un ton localisé adapté au contexte ouest-africain ("On est ensemble", "Ça avance bien").

    🧠 **RAG Hybride avec Fusion Intelligente** :
    Le système combine en temps réel 3 sources documentaires :
    - **Base Officielle** : Contenus pédagogiques de formation entrepreneuriale.
    - **Documents Personnels** : Factures, contrats, reçus uploadés par l'utilisatrice (avec OCR intégré pour les images).
    - **Algorithme de Fusion** : Selon l'intention de la question, le moteur applique les stratégies personal_priority, official_priority ou balanced pour construire le contexte le plus pertinent.

    🛠️ **Défis Techniques Résolus** :
    - **Deadlocks d'indexation vectorielle** : Remplacement de threading.Lock() par threading.RLock() (verrou réentrant) pour éliminer 100% des freezes lors des uploads massifs en concurrence.
    - **Instabilité réseau mobile (Afrique de l'Ouest)** : Système multi-niveaux de résilience IP avec matching sur sous-réseau /16 et /8 pour compenser les rotations IP mobile (Orange/MTN).
    - **Pipeline documentaire robuste** : Ingestion asynchrone (PDF, DOCX, TXT, Images) avec déduplication par hash SHA-256, chunking adaptatif et analyse qualitative IA.

    ⚙️ **Architecture Technique** :
    - **Backend** : FastAPI (Python 3.11) asynchrone, PostgreSQL + SQLAlchemy, SQLite pour la mémoire long terme.
    - **IA Vocale** : OpenAI Whisper (STT), ElevenLabs (TTS multi-langue), GPT-4o / Claude 3 pour la génération.
    - **RAG** : FAISS (recherche vectorielle) + all-MiniLM-L6-v2 (embeddings sémantiques).
    - **Mobile** : Application Flutter cross-platform avec interface voice-first.
    - **DevOps** : Docker Compose (4 conteneurs), proxy Caddy (HTTPS auto Let's Encrypt), rate limiting et pg_dump automatique."""

    # 5. Create project
    project, created = Project.objects.get_or_create(
        title="AmazoOn",
        defaults={
            "slug": "amazoon",
            "description": "Chatbot éducatif vocal & assistant RAG pour l'entrepreneuriat féminin en Afrique de l'Ouest.",
            "detailed_description": detailed_desc.strip(),
            "featured_image": "projects/featured/amazoon_hero.png",
            "demo_url": "#",
            "source_url": "#",
            "status": "published",
            "featured": True,
            "owner": owner,
            "category": category,
        }
    )

    if not created:
        project.owner = owner
        project.category = category
        project.save()

    project.technologies.set(techs)


def remove_amazoon(apps, schema_editor):
    Project = apps.get_model('portfolio', 'Project')
    Project.objects.filter(slug='amazoon').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_seed_remedia'),
    ]

    operations = [
        migrations.RunPython(seed_amazoon, reverse_code=remove_amazoon),
    ]
